// <auto-generated />
namespace PoliceServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class user_change_OrganizationCode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_change_OrganizationCode));
        
        string IMigrationMetadata.Id
        {
            get { return "201808280952492_user_change_OrganizationCode"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
